using Microsoft.AspNetCore.Mvc;
using System.Linq;
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDBSharding.Models;

namespace MongoDBSharding.Endpoints;

public class CreateOrderRequest
{
    public string? OrderId { get; set; }
}

public static class ShardingApi
{
    public static void MapShardingEndpoints(this IEndpointRouteBuilder app)
    {
        // 1. Sharded database endpoints (Orders) using the unified MongoDbContext
        var shardingGroup = app.MapGroup("/api/sharding");

        shardingGroup.MapPost("/order/create", async (MongoDbContext db, [FromBody] CreateOrderRequest? req) =>
        {
            var orderId = (!string.IsNullOrWhiteSpace(req?.OrderId)) ? req.OrderId : Guid.NewGuid().ToString("N").ToUpper();
            var customerName = "WebGuest_" + new Random().Next(1000, 9999);
            var amount = Math.Round((decimal)(new Random().NextDouble() * 500 + 5), 2);

            var randCountry = await db.Countries
                .Aggregate()
                .Sample(1)
                .FirstAsync();

            var order = new Order
            {
                OrderId = orderId,
                CustomerName = customerName,
                Amount = amount,
                Status = "Completed",
                CountryId = randCountry.Id,
                CreatedAt = DateTime.UtcNow
            };

            await db.Orders.InsertOneAsync(order);

            return Results.Ok(new
            {
                ShardKeyUsed = "OrderId",
                ShardKeyValue = orderId,
            });
        });


        shardingGroup.MapGet("/order/list", async (MongoDbContext db) =>
        {
            var results = await db.Orders.Find(_ => true).ToListAsync();
            return Results.Ok(results);
        });

        shardingGroup.MapGet("/order/list-with-country", async (MongoDbContext db) =>
        {
            // 備註：因為 Orders 與 Countries 現在都位於同一個資料庫 (ShardingDb)，
            // 兩者屬於同一個 MongoDB 連線實例，因此可以直接使用 MongoDB 原生的 $lookup 進行高效的跨表關聯查詢（透過 LINQ Join）。
            var query = from order in db.Orders.AsQueryable()
                        join country in db.Countries.AsQueryable() on order.CountryId equals country.Id into joinedCountries
                        select new OrderDto
                        {
                            Id = order.Id,
                            OrderId = order.OrderId,
                            CustomerName = order.CustomerName,
                            Amount = order.Amount,
                            Status = order.Status,
                            CountryId = order.CountryId,
                            CreatedAt = order.CreatedAt,
                            Country = joinedCountries.FirstOrDefault()
                        };

            var results = await MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync((IAsyncCursorSource<OrderDto>)query);
            return Results.Ok(results);
        });

        // 2. Standalone database endpoints (MyCountry) using the unified MongoDbContext
        var countryGroup = app.MapGroup("/api/country");

        countryGroup.MapPost("/create", async (MongoDbContext db, [FromBody] MyCountry country) =>
        {
            if (string.IsNullOrWhiteSpace(country.Name) || string.IsNullOrWhiteSpace(country.Code))
            {
                return Results.BadRequest(new { Message = "Country Name and Code are required." });
            }

            country.Id = null; // Generated by MongoDB as ObjectId
            country.CreatedAt = DateTime.UtcNow;

            await db.Countries.InsertOneAsync(country);

            return Results.Ok(new
            {
                Message = "Country added successfully!",
                Country = country
            });
        });

        countryGroup.MapGet("/list", async (MongoDbContext db) =>
        {
            var results = await db.Countries.Find(_ => true).ToListAsync();
            return Results.Ok(results);
        });
    }
}

