using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using MongoDBSharding.Models;

namespace MongoDBSharding.Endpoints;

public class CreateOrderRequest
{
    public string? OrderId { get; set; }
}

public static class ShardingApi
{
    public static void MapShardingEndpoints(this IEndpointRouteBuilder app)
    {
        if (app is IApplicationBuilder appBuilder)
        {
            appBuilder.Use(async (context, next) =>
            {
                context.Response.Headers["X-Instance-Name"] = Environment.MachineName;
                await next();
            });
        }

        // 1. Sharded database endpoints (Orders) using the unified MongoDbContext
        var shardingGroup = app.MapGroup("/api/sharding");

        shardingGroup.MapGet("/instance", () => Results.Ok(new { InstanceName = Environment.MachineName }));

        shardingGroup.MapPost("/order/create", async (MongoDbContext db, [FromBody] CreateOrderRequest? req) =>
        {
            var orderId = (!string.IsNullOrWhiteSpace(req?.OrderId)) ? req.OrderId : Guid.NewGuid().ToString("N").ToUpper();
            var customerName = "WebGuest_" + new Random().Next(1000, 9999);
            var amount = Math.Round((decimal)(new Random().NextDouble() * 500 + 5), 2);

            var randCountry = await db.Countries
                .Aggregate()
                .Sample(1)
                .FirstAsync();

            var order = new Order
            {
                OrderId = orderId,
                CustomerName = customerName,
                Amount = amount,
                Status = "Completed",
                CountryId = randCountry.Id,
                CreatedAt = DateTime.UtcNow
            };

            await db.Orders.InsertOneAsync(order);

            return Results.Ok(new
            {
                ShardKeyUsed = "OrderId",
                ShardKeyValue = orderId,
            });
        });


        shardingGroup.MapGet("/order/list", async (MongoDbContext db) =>
        {
            var results = await db.Orders.Find(_ => true).ToListAsync();
            return Results.Ok(results);
        });

        shardingGroup.MapGet("/order/get", async (MongoDbContext db, [FromQuery] string orderId, [FromQuery] string? comment) =>
        {
            var options = new FindOptions();
            if (!string.IsNullOrWhiteSpace(comment))
            {
                options.Comment = comment;
            }
            var result = await db.Orders.Find(o => o.OrderId == orderId, options).FirstOrDefaultAsync();
            if (result == null)
            {
                return Results.NotFound(new { Message = $"Order {orderId} not found." });
            }
            return Results.Ok(result);
        });

        var countryGroup = app.MapGroup("/api/country");

        countryGroup.MapPost("/create", async (MongoDbContext db, [FromBody] MyCountry country) =>
        {
            if (string.IsNullOrWhiteSpace(country.Name) || string.IsNullOrWhiteSpace(country.Code))
            {
                return Results.BadRequest(new { Message = "Country Name and Code are required." });
            }

            country.Id = null; // Generated by MongoDB as ObjectId
            country.CreatedAt = DateTime.UtcNow;

            await db.Countries.InsertOneAsync(country);

            return Results.Ok(new
            {
                Message = "Country added successfully!",
                Country = country
            });
        });
    }
}

