apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          command: [mongos, --configdb, configReplSet/configsvr:15561, --port, "15564", --bind_ip_all]
          ports:
            - containerPort: 15564
---
apiVersion: v1
kind: Service
metadata:
  name: mongos
spec:
  ports:
    - port: 15564
  selector:
    app: mongos
