apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapi-pod
  template:
    metadata:
      labels:
        app: mywebapi-pod
    spec:
      initContainers:
        - name: mywait-for-setup
          image: mongo:latest
          command: [bash, -c, "until mongosh --host mymongos-service --port 15564 --eval 'if(db.adminCommand({listShards:1}).shards.length<3)throw 1' &>/dev/null; do sleep 2; done"]
      containers:
        - name: mywebapi-container
          image: mywebapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapi-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: mywebapi-pod
