// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MongoDBSharding.Test.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MongoDB讀寫分離與實體分片精準驗證Feature : object, Xunit.IClassFixture<MongoDB讀寫分離與實體分片精準驗證Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("zh-TW"), "Features", "MongoDB 讀寫分離與實體分片精準驗證", ("  為了確保國家資料（Unsharded）與訂單資料（Sharded with Zone）能正確地路由至目標實體分片，\r\n  並且驗證讀寫分離機制（seconda" +
                "ryPreferred）能將讀取流量均勻分配到所有的唯讀副本（Secondary 節點），\r\n  作為一個系統架構工程師，\r\n  我希望在 Web API 上進" +
                "行寫入與查詢操作，並直接透過實體資料庫連線與 K8s 狀態來驗證其物理分佈。"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ShardingAndReadReplica.feature"
#line hidden
        
        public MongoDB讀寫分離與實體分片精準驗證Feature(MongoDB讀寫分離與實體分片精準驗證Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="1. 驗證國家資料僅存在於預設分片而訂單資料均勻分佈於分片一與分片二")]
        [Xunit.TraitAttribute("FeatureTitle", "MongoDB 讀寫分離與實體分片精準驗證")]
        [Xunit.TraitAttribute("Description", "1. 驗證國家資料僅存在於預設分片而訂單資料均勻分佈於分片一與分片二")]
        public async System.Threading.Tasks.Task _1_驗證國家資料僅存在於預設分片而訂單資料均勻分佈於分片一與分片二()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1. 驗證國家資料僅存在於預設分片而訂單資料均勻分佈於分片一與分片二", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("系統 Web API 服務已成功啟動且各個實體分片皆可連線", ((string)(null)), ((global::Reqnroll.Table)(null)), "假設");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Code"});
                table1.AddRow(new string[] {
                            "台灣",
                            "TW"});
                table1.AddRow(new string[] {
                            "日本",
                            "JP"});
#line 10
    await testRunner.WhenAsync("我呼叫建立國家 API 建立以下 2 個國家:", ((string)(null)), table1, "當");
#line hidden
#line 14
    await testRunner.ThenAsync("我直接連線預設分片 \"mydefault\" 查詢，應該要在 \"MyCountry\" 集合中找到剛好 2 筆國家資料", ((string)(null)), ((global::Reqnroll.Table)(null)), "那麼");
#line hidden
#line 15
    await testRunner.AndAsync("我直接連線 \"shard1\" 與 \"shard2\" 查詢，在 \"MyCountry\" 集合中不應該存有任何資料", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "OrderId",
                            "CustomerName",
                            "Amount"});
                table2.AddRow(new string[] {
                            "ORDER_ID_03",
                            "Guest_D",
                            "90.0"});
                table2.AddRow(new string[] {
                            "ORDER_ID_05",
                            "Guest_E",
                            "150.7"});
#line 17
    await testRunner.WhenAsync("我呼叫建立訂單 API 並指定以下 2 個特定的訂單編號:", ((string)(null)), table2, "當");
#line hidden
#line 21
    await testRunner.ThenAsync("我直接連線 \"mydefault\" 查詢，不應該存在訂單 \"ORDER_ID_03\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "那麼");
#line hidden
#line 22
    await testRunner.AndAsync("我直接連線 \"mydefault\" 查詢，不應該存在訂單 \"ORDER_ID_05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 23
    await testRunner.AndAsync("我直接連線 \"shard1\" 查詢，應該存在訂單 \"ORDER_ID_03\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 24
    await testRunner.AndAsync("我直接連線 \"shard1\" 查詢，不應該存在訂單 \"ORDER_ID_05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 25
    await testRunner.AndAsync("我直接連線 \"shard2\" 查詢，應該存在訂單 \"ORDER_ID_05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 26
    await testRunner.AndAsync("我直接連線 \"shard2\" 查詢，不應該存在訂單 \"ORDER_ID_03\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 27
    await testRunner.AndAsync("我直接連線 \"27017\" 查詢，應該存在訂單 \"ORDER_ID_03\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 28
    await testRunner.AndAsync("我直接連線 \"27017\" 查詢，應該存在訂單 \"ORDER_ID_05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="2. 驗證多次特定 OrderId 查詢時流量均勻路由至對應 Shard 的唯讀副本 (Secondary)")]
        [Xunit.TraitAttribute("FeatureTitle", "MongoDB 讀寫分離與實體分片精準驗證")]
        [Xunit.TraitAttribute("Description", "2. 驗證多次特定 OrderId 查詢時流量均勻路由至對應 Shard 的唯讀副本 (Secondary)")]
        public async System.Threading.Tasks.Task _2_驗證多次特定OrderId查詢時流量均勻路由至對應Shard的唯讀副本Secondary()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2. 驗證多次特定 OrderId 查詢時流量均勻路由至對應 Shard 的唯讀副本 (Secondary)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("系統 Web API 服務已成功啟動且各個實體分片皆可連線", ((string)(null)), ((global::Reqnroll.Table)(null)), "假設");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Code"});
                table3.AddRow(new string[] {
                            "台灣",
                            "TW"});
#line 32
    await testRunner.WhenAsync("我呼叫建立國家 API 建立以下 1 個國家:", ((string)(null)), table3, "當");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "OrderId"});
                table4.AddRow(new string[] {
                            "ORDER_ID_03"});
                table4.AddRow(new string[] {
                            "ORDER_ID_05"});
#line 35
    await testRunner.AndAsync("我呼叫建立訂單 API 並指定以下 2 個特定的訂單編號:", ((string)(null)), table4, "而且");
#line hidden
#line 39
    await testRunner.AndAsync("我記錄所有分片唯讀副本（\"shard1-1\", \"shard1-2\", \"shard2-1\", \"shard2-2\"）的初始查詢計數器", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 40
    await testRunner.AndAsync("我使用特定 OrderId 查詢訂單 33 次，其中 \"ORDER_ID_03\" 查詢 11 次，\"ORDER_ID_05\" 查詢 22 次", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
#line 41
    await testRunner.ThenAsync("我再次讀取所有分片唯讀副本的查詢次數，\"shard1-1\" 與 \"shard1-2\" 總和應該增加 11 次", ((string)(null)), ((global::Reqnroll.Table)(null)), "那麼");
#line hidden
#line 42
    await testRunner.AndAsync("\"shard2-1\" 與 \"shard2-2\" 總和應該增加 22 次", ((string)(null)), ((global::Reqnroll.Table)(null)), "而且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="3. 驗證 Web API 負載平衡與多個實體間請求均勻分配")]
        [Xunit.TraitAttribute("FeatureTitle", "MongoDB 讀寫分離與實體分片精準驗證")]
        [Xunit.TraitAttribute("Description", "3. 驗證 Web API 負載平衡與多個實體間請求均勻分配")]
        public async System.Threading.Tasks.Task _3_驗證WebAPI負載平衡與多個實體間請求均勻分配()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3. 驗證 Web API 負載平衡與多個實體間請求均勻分配", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("系統 Web API 服務已成功部署 2 個實體且均已就緒", ((string)(null)), ((global::Reqnroll.Table)(null)), "假設");
#line hidden
#line 46
    await testRunner.WhenAsync("我呼叫 Web API 測試負載平衡共 100 次", ((string)(null)), ((global::Reqnroll.Table)(null)), "當");
#line hidden
#line 47
    await testRunner.ThenAsync("這些請求應該要大致平均分配給 2 個不同的 Web API 實體", ((string)(null)), ((global::Reqnroll.Table)(null)), "那麼");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MongoDB讀寫分離與實體分片精準驗證Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MongoDB讀寫分離與實體分片精準驗證Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
